#!/usr/bin/env bash
# Build the Paper-II PDF (companion: SEDE_foundations.md) with the same
# mdmath + pandoc(+template.tex,+header.tex) + xelatex toolchain as build_tex.sh.
# Figures are embedded as VECTOR PDFs (../../output/*.pdf), generated by
# make_foundations_vector.py. Run from paper/:  bash build_foundations.sh
#   (regenerate the vector figures first:  python make_foundations_vector.py)
set -e
cd "$(dirname "$0")"
mkdir -p tex

# 1. assemble build markdown (inline-math wrap + title/abstract -> YAML)
python3 makedoc.py SEDE_foundations.md .SF.proc.md
trap 'rm -f .SF.proc.md' EXIT

# 2. markdown -> standalone LaTeX
pandoc -f markdown-superscript-subscript .SF.proc.md -o tex/SEDE_foundations.tex \
  --standalone \
  --shift-heading-level-by=-1 \
  --template=template.tex \
  -H header.tex \
  -V mainfont="STIX Two Text" \
  -V geometry:margin=1in \
  -V fontsize=10pt \
  -V colorlinks=true -V linkcolor=RoyalBlue -V urlcolor=RoyalBlue \
  --toc --toc-depth=2

# 3. fix figure path depth (paper/tex/ -> repo/output is ../../output) and switch the
#    output/*.png figure references to the VECTOR *.pdf (make_foundations_vector.py)
perl -0pi -e 's#\{\.\./output/#{../../output/#g' tex/SEDE_foundations.tex
perl -0pi -e 's#(\.\./\.\./output/[A-Za-z0-9_]+)\.png\}#$1.pdf}#g' tex/SEDE_foundations.tex

# 4. compile (xelatex twice: ToC + cross-refs; references inline, no bibtex)
( cd tex && xelatex -interaction=nonstopmode SEDE_foundations.tex >SF.build.log 2>&1 \
            && xelatex -interaction=nonstopmode SEDE_foundations.tex >>SF.build.log 2>&1 ) \
  || { echo "TEX BUILD FAILED — see tex/SF.build.log"; grep -A2 '^!' tex/SF.build.log | head -20; exit 1; }

echo "built paper/tex/SEDE_foundations.tex  ->  tex/SEDE_foundations.pdf"
grep -ci "missing character" tex/SF.build.log | awk '{if($1>0) print "note: "$1" missing-glyph warnings"; else print "no missing glyphs"}'
grep -cE '\\includegraphics' tex/SEDE_foundations.tex | awk '{print $1" figures embedded"}'
